// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.web.servant.center;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class bidArrayItem {

	@TarsStructProperty(order = 1, isRequire = true)
	public double bidPrice = 0D;
	@TarsStructProperty(order = 2, isRequire = true)
	public int bidVolume = 0;

	public double getBidPrice() {
		return bidPrice;
	}

	public void setBidPrice(double bidPrice) {
		this.bidPrice = bidPrice;
	}

	public int getBidVolume() {
		return bidVolume;
	}

	public void setBidVolume(int bidVolume) {
		this.bidVolume = bidVolume;
	}

	public bidArrayItem() {
	}

	public bidArrayItem(double bidPrice, int bidVolume) {
		this.bidPrice = bidPrice;
		this.bidVolume = bidVolume;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(bidPrice);
		result = prime * result + TarsUtil.hashCode(bidVolume);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof bidArrayItem)) {
			return false;
		}
		bidArrayItem other = (bidArrayItem) obj;
		return (
			TarsUtil.equals(bidPrice, other.bidPrice) &&
			TarsUtil.equals(bidVolume, other.bidVolume) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(bidPrice, 1);
		_os.write(bidVolume, 2);
	}


	public void readFrom(TarsInputStream _is) {
		this.bidPrice = _is.read(bidPrice, 1, true);
		this.bidVolume = _is.read(bidVolume, 2, true);
	}

}
