// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.web.servant.center;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class instrumentCommissionQueryResponse {

	@TarsStructProperty(order = 1, isRequire = true)
	public String typeId = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public int requestId = 0;
	@TarsStructProperty(order = 3, isRequire = true)
	public int errcode = 0;
	@TarsStructProperty(order = 4, isRequire = true)
	public String errmsg = "";
	@TarsStructProperty(order = 5, isRequire = true)
	public String instrumentId = "";
	@TarsStructProperty(order = 6, isRequire = true)
	public double openRatioByMoney = 0D;
	@TarsStructProperty(order = 7, isRequire = true)
	public double openRatioByVolume = 0D;
	@TarsStructProperty(order = 8, isRequire = true)
	public double closeRatioByMoney = 0D;
	@TarsStructProperty(order = 9, isRequire = true)
	public double closeRatioByVolume = 0D;

	public String getTypeId() {
		return typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	public int getRequestId() {
		return requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	public int getErrcode() {
		return errcode;
	}

	public void setErrcode(int errcode) {
		this.errcode = errcode;
	}

	public String getErrmsg() {
		return errmsg;
	}

	public void setErrmsg(String errmsg) {
		this.errmsg = errmsg;
	}

	public String getInstrumentId() {
		return instrumentId;
	}

	public void setInstrumentId(String instrumentId) {
		this.instrumentId = instrumentId;
	}

	public double getOpenRatioByMoney() {
		return openRatioByMoney;
	}

	public void setOpenRatioByMoney(double openRatioByMoney) {
		this.openRatioByMoney = openRatioByMoney;
	}

	public double getOpenRatioByVolume() {
		return openRatioByVolume;
	}

	public void setOpenRatioByVolume(double openRatioByVolume) {
		this.openRatioByVolume = openRatioByVolume;
	}

	public double getCloseRatioByMoney() {
		return closeRatioByMoney;
	}

	public void setCloseRatioByMoney(double closeRatioByMoney) {
		this.closeRatioByMoney = closeRatioByMoney;
	}

	public double getCloseRatioByVolume() {
		return closeRatioByVolume;
	}

	public void setCloseRatioByVolume(double closeRatioByVolume) {
		this.closeRatioByVolume = closeRatioByVolume;
	}

	public instrumentCommissionQueryResponse() {
	}

	public instrumentCommissionQueryResponse(String typeId, int requestId, int errcode, String errmsg, String instrumentId, double openRatioByMoney, double openRatioByVolume, double closeRatioByMoney, double closeRatioByVolume) {
		this.typeId = typeId;
		this.requestId = requestId;
		this.errcode = errcode;
		this.errmsg = errmsg;
		this.instrumentId = instrumentId;
		this.openRatioByMoney = openRatioByMoney;
		this.openRatioByVolume = openRatioByVolume;
		this.closeRatioByMoney = closeRatioByMoney;
		this.closeRatioByVolume = closeRatioByVolume;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(typeId);
		result = prime * result + TarsUtil.hashCode(requestId);
		result = prime * result + TarsUtil.hashCode(errcode);
		result = prime * result + TarsUtil.hashCode(errmsg);
		result = prime * result + TarsUtil.hashCode(instrumentId);
		result = prime * result + TarsUtil.hashCode(openRatioByMoney);
		result = prime * result + TarsUtil.hashCode(openRatioByVolume);
		result = prime * result + TarsUtil.hashCode(closeRatioByMoney);
		result = prime * result + TarsUtil.hashCode(closeRatioByVolume);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof instrumentCommissionQueryResponse)) {
			return false;
		}
		instrumentCommissionQueryResponse other = (instrumentCommissionQueryResponse) obj;
		return (
			TarsUtil.equals(typeId, other.typeId) &&
			TarsUtil.equals(requestId, other.requestId) &&
			TarsUtil.equals(errcode, other.errcode) &&
			TarsUtil.equals(errmsg, other.errmsg) &&
			TarsUtil.equals(instrumentId, other.instrumentId) &&
			TarsUtil.equals(openRatioByMoney, other.openRatioByMoney) &&
			TarsUtil.equals(openRatioByVolume, other.openRatioByVolume) &&
			TarsUtil.equals(closeRatioByMoney, other.closeRatioByMoney) &&
			TarsUtil.equals(closeRatioByVolume, other.closeRatioByVolume) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(typeId, 1);
		_os.write(requestId, 2);
		_os.write(errcode, 3);
		_os.write(errmsg, 4);
		_os.write(instrumentId, 5);
		_os.write(openRatioByMoney, 6);
		_os.write(openRatioByVolume, 7);
		_os.write(closeRatioByMoney, 8);
		_os.write(closeRatioByVolume, 9);
	}


	public void readFrom(TarsInputStream _is) {
		this.typeId = _is.readString(1, true);
		this.requestId = _is.read(requestId, 2, true);
		this.errcode = _is.read(errcode, 3, true);
		this.errmsg = _is.readString(4, true);
		this.instrumentId = _is.readString(5, true);
		this.openRatioByMoney = _is.read(openRatioByMoney, 6, true);
		this.openRatioByVolume = _is.read(openRatioByVolume, 7, true);
		this.closeRatioByMoney = _is.read(closeRatioByMoney, 8, true);
		this.closeRatioByVolume = _is.read(closeRatioByVolume, 9, true);
	}

}
