// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.web.servant.center;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class instrumentQueryResponse {

	@TarsStructProperty(order = 1, isRequire = true)
	public String typeId = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public int requestId = 0;
	@TarsStructProperty(order = 3, isRequire = true)
	public int errcode = 0;
	@TarsStructProperty(order = 4, isRequire = true)
	public String errmsg = "";
	@TarsStructProperty(order = 5, isRequire = true)
	public String instrumentId = "";
	@TarsStructProperty(order = 6, isRequire = true)
	public String instrumentName = "";
	@TarsStructProperty(order = 7, isRequire = true)
	public int maxMarketOrderVolume = 0;
	@TarsStructProperty(order = 8, isRequire = true)
	public int minMarketOrderVolume = 0;
	@TarsStructProperty(order = 9, isRequire = true)
	public int volumeMultiple = 0;
	@TarsStructProperty(order = 10, isRequire = true)
	public double priceTick = 0D;
	@TarsStructProperty(order = 11, isRequire = true)
	public String createDate = "";
	@TarsStructProperty(order = 12, isRequire = true)
	public String openDate = "";
	@TarsStructProperty(order = 13, isRequire = true)
	public String expireDate = "";

	public String getTypeId() {
		return typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	public int getRequestId() {
		return requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	public int getErrcode() {
		return errcode;
	}

	public void setErrcode(int errcode) {
		this.errcode = errcode;
	}

	public String getErrmsg() {
		return errmsg;
	}

	public void setErrmsg(String errmsg) {
		this.errmsg = errmsg;
	}

	public String getInstrumentId() {
		return instrumentId;
	}

	public void setInstrumentId(String instrumentId) {
		this.instrumentId = instrumentId;
	}

	public String getInstrumentName() {
		return instrumentName;
	}

	public void setInstrumentName(String instrumentName) {
		this.instrumentName = instrumentName;
	}

	public int getMaxMarketOrderVolume() {
		return maxMarketOrderVolume;
	}

	public void setMaxMarketOrderVolume(int maxMarketOrderVolume) {
		this.maxMarketOrderVolume = maxMarketOrderVolume;
	}

	public int getMinMarketOrderVolume() {
		return minMarketOrderVolume;
	}

	public void setMinMarketOrderVolume(int minMarketOrderVolume) {
		this.minMarketOrderVolume = minMarketOrderVolume;
	}

	public int getVolumeMultiple() {
		return volumeMultiple;
	}

	public void setVolumeMultiple(int volumeMultiple) {
		this.volumeMultiple = volumeMultiple;
	}

	public double getPriceTick() {
		return priceTick;
	}

	public void setPriceTick(double priceTick) {
		this.priceTick = priceTick;
	}

	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getOpenDate() {
		return openDate;
	}

	public void setOpenDate(String openDate) {
		this.openDate = openDate;
	}

	public String getExpireDate() {
		return expireDate;
	}

	public void setExpireDate(String expireDate) {
		this.expireDate = expireDate;
	}

	public instrumentQueryResponse() {
	}

	public instrumentQueryResponse(String typeId, int requestId, int errcode, String errmsg, String instrumentId, String instrumentName, int maxMarketOrderVolume, int minMarketOrderVolume, int volumeMultiple, double priceTick, String createDate, String openDate, String expireDate) {
		this.typeId = typeId;
		this.requestId = requestId;
		this.errcode = errcode;
		this.errmsg = errmsg;
		this.instrumentId = instrumentId;
		this.instrumentName = instrumentName;
		this.maxMarketOrderVolume = maxMarketOrderVolume;
		this.minMarketOrderVolume = minMarketOrderVolume;
		this.volumeMultiple = volumeMultiple;
		this.priceTick = priceTick;
		this.createDate = createDate;
		this.openDate = openDate;
		this.expireDate = expireDate;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(typeId);
		result = prime * result + TarsUtil.hashCode(requestId);
		result = prime * result + TarsUtil.hashCode(errcode);
		result = prime * result + TarsUtil.hashCode(errmsg);
		result = prime * result + TarsUtil.hashCode(instrumentId);
		result = prime * result + TarsUtil.hashCode(instrumentName);
		result = prime * result + TarsUtil.hashCode(maxMarketOrderVolume);
		result = prime * result + TarsUtil.hashCode(minMarketOrderVolume);
		result = prime * result + TarsUtil.hashCode(volumeMultiple);
		result = prime * result + TarsUtil.hashCode(priceTick);
		result = prime * result + TarsUtil.hashCode(createDate);
		result = prime * result + TarsUtil.hashCode(openDate);
		result = prime * result + TarsUtil.hashCode(expireDate);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof instrumentQueryResponse)) {
			return false;
		}
		instrumentQueryResponse other = (instrumentQueryResponse) obj;
		return (
			TarsUtil.equals(typeId, other.typeId) &&
			TarsUtil.equals(requestId, other.requestId) &&
			TarsUtil.equals(errcode, other.errcode) &&
			TarsUtil.equals(errmsg, other.errmsg) &&
			TarsUtil.equals(instrumentId, other.instrumentId) &&
			TarsUtil.equals(instrumentName, other.instrumentName) &&
			TarsUtil.equals(maxMarketOrderVolume, other.maxMarketOrderVolume) &&
			TarsUtil.equals(minMarketOrderVolume, other.minMarketOrderVolume) &&
			TarsUtil.equals(volumeMultiple, other.volumeMultiple) &&
			TarsUtil.equals(priceTick, other.priceTick) &&
			TarsUtil.equals(createDate, other.createDate) &&
			TarsUtil.equals(openDate, other.openDate) &&
			TarsUtil.equals(expireDate, other.expireDate) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(typeId, 1);
		_os.write(requestId, 2);
		_os.write(errcode, 3);
		_os.write(errmsg, 4);
		_os.write(instrumentId, 5);
		_os.write(instrumentName, 6);
		_os.write(maxMarketOrderVolume, 7);
		_os.write(minMarketOrderVolume, 8);
		_os.write(volumeMultiple, 9);
		_os.write(priceTick, 10);
		_os.write(createDate, 11);
		_os.write(openDate, 12);
		_os.write(expireDate, 13);
	}


	public void readFrom(TarsInputStream _is) {
		this.typeId = _is.readString(1, true);
		this.requestId = _is.read(requestId, 2, true);
		this.errcode = _is.read(errcode, 3, true);
		this.errmsg = _is.readString(4, true);
		this.instrumentId = _is.readString(5, true);
		this.instrumentName = _is.readString(6, true);
		this.maxMarketOrderVolume = _is.read(maxMarketOrderVolume, 7, true);
		this.minMarketOrderVolume = _is.read(minMarketOrderVolume, 8, true);
		this.volumeMultiple = _is.read(volumeMultiple, 9, true);
		this.priceTick = _is.read(priceTick, 10, true);
		this.createDate = _is.readString(11, true);
		this.openDate = _is.readString(12, true);
		this.expireDate = _is.readString(13, true);
	}

}
