// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.web.servant.center;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class orderOpenResponse {

	@TarsStructProperty(order = 1, isRequire = true)
	public String typeId = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public int requestId = 0;
	@TarsStructProperty(order = 3, isRequire = true)
	public int errcode = 0;
	@TarsStructProperty(order = 4, isRequire = true)
	public String errmsg = "";
	@TarsStructProperty(order = 5, isRequire = true)
	public String instrumentId = "";
	@TarsStructProperty(order = 6, isRequire = true)
	public java.util.List<tradeItem> tradeArrayItems = null;

	public String getTypeId() {
		return typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	public int getRequestId() {
		return requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	public int getErrcode() {
		return errcode;
	}

	public void setErrcode(int errcode) {
		this.errcode = errcode;
	}

	public String getErrmsg() {
		return errmsg;
	}

	public void setErrmsg(String errmsg) {
		this.errmsg = errmsg;
	}

	public String getInstrumentId() {
		return instrumentId;
	}

	public void setInstrumentId(String instrumentId) {
		this.instrumentId = instrumentId;
	}

	public java.util.List<tradeItem> getTradeArrayItems() {
		return tradeArrayItems;
	}

	public void setTradeArrayItems(java.util.List<tradeItem> tradeArrayItems) {
		this.tradeArrayItems = tradeArrayItems;
	}

	public orderOpenResponse() {
	}

	public orderOpenResponse(String typeId, int requestId, int errcode, String errmsg, String instrumentId, java.util.List<tradeItem> tradeArrayItems) {
		this.typeId = typeId;
		this.requestId = requestId;
		this.errcode = errcode;
		this.errmsg = errmsg;
		this.instrumentId = instrumentId;
		this.tradeArrayItems = tradeArrayItems;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(typeId);
		result = prime * result + TarsUtil.hashCode(requestId);
		result = prime * result + TarsUtil.hashCode(errcode);
		result = prime * result + TarsUtil.hashCode(errmsg);
		result = prime * result + TarsUtil.hashCode(instrumentId);
		result = prime * result + TarsUtil.hashCode(tradeArrayItems);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof orderOpenResponse)) {
			return false;
		}
		orderOpenResponse other = (orderOpenResponse) obj;
		return (
			TarsUtil.equals(typeId, other.typeId) &&
			TarsUtil.equals(requestId, other.requestId) &&
			TarsUtil.equals(errcode, other.errcode) &&
			TarsUtil.equals(errmsg, other.errmsg) &&
			TarsUtil.equals(instrumentId, other.instrumentId) &&
			TarsUtil.equals(tradeArrayItems, other.tradeArrayItems) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(typeId, 1);
		_os.write(requestId, 2);
		_os.write(errcode, 3);
		_os.write(errmsg, 4);
		_os.write(instrumentId, 5);
		_os.write(tradeArrayItems, 6);
	}

	static java.util.List<tradeItem> cache_tradeArrayItems;
	static { 
		cache_tradeArrayItems = new java.util.ArrayList<tradeItem>();
		tradeItem var_1 = new tradeItem();
		cache_tradeArrayItems.add(var_1);
	}

	public void readFrom(TarsInputStream _is) {
		this.typeId = _is.readString(1, true);
		this.requestId = _is.read(requestId, 2, true);
		this.errcode = _is.read(errcode, 3, true);
		this.errmsg = _is.readString(4, true);
		this.instrumentId = _is.readString(5, true);
		this.tradeArrayItems = (java.util.List<tradeItem>) _is.read(cache_tradeArrayItems, 6, true);
	}

}
