// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.web.servant.center;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class orderOpenRequest {

	@TarsStructProperty(order = 1, isRequire = true)
	public String typeId = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public int requestId = 0;
	@TarsStructProperty(order = 3, isRequire = true)
	public String brokerId = "";
	@TarsStructProperty(order = 4, isRequire = true)
	public String userId = "";
	@TarsStructProperty(order = 5, isRequire = true)
	public String instrumentId = "";
	@TarsStructProperty(order = 6, isRequire = true)
	public int orderDirection = 0;
	@TarsStructProperty(order = 7, isRequire = true)
	public int volumeTotalOriginal = 0;
	@TarsStructProperty(order = 8, isRequire = false)
	public int orderTimeout = 5000;

	public String getTypeId() {
		return typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	public int getRequestId() {
		return requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	public String getBrokerId() {
		return brokerId;
	}

	public void setBrokerId(String brokerId) {
		this.brokerId = brokerId;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getInstrumentId() {
		return instrumentId;
	}

	public void setInstrumentId(String instrumentId) {
		this.instrumentId = instrumentId;
	}

	public int getOrderDirection() {
		return orderDirection;
	}

	public void setOrderDirection(int orderDirection) {
		this.orderDirection = orderDirection;
	}

	public int getVolumeTotalOriginal() {
		return volumeTotalOriginal;
	}

	public void setVolumeTotalOriginal(int volumeTotalOriginal) {
		this.volumeTotalOriginal = volumeTotalOriginal;
	}

	public int getOrderTimeout() {
		return orderTimeout;
	}

	public void setOrderTimeout(int orderTimeout) {
		this.orderTimeout = orderTimeout;
	}

	public orderOpenRequest() {
	}

	public orderOpenRequest(String typeId, int requestId, String brokerId, String userId, String instrumentId, int orderDirection, int volumeTotalOriginal, int orderTimeout) {
		this.typeId = typeId;
		this.requestId = requestId;
		this.brokerId = brokerId;
		this.userId = userId;
		this.instrumentId = instrumentId;
		this.orderDirection = orderDirection;
		this.volumeTotalOriginal = volumeTotalOriginal;
		this.orderTimeout = orderTimeout;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(typeId);
		result = prime * result + TarsUtil.hashCode(requestId);
		result = prime * result + TarsUtil.hashCode(brokerId);
		result = prime * result + TarsUtil.hashCode(userId);
		result = prime * result + TarsUtil.hashCode(instrumentId);
		result = prime * result + TarsUtil.hashCode(orderDirection);
		result = prime * result + TarsUtil.hashCode(volumeTotalOriginal);
		result = prime * result + TarsUtil.hashCode(orderTimeout);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof orderOpenRequest)) {
			return false;
		}
		orderOpenRequest other = (orderOpenRequest) obj;
		return (
			TarsUtil.equals(typeId, other.typeId) &&
			TarsUtil.equals(requestId, other.requestId) &&
			TarsUtil.equals(brokerId, other.brokerId) &&
			TarsUtil.equals(userId, other.userId) &&
			TarsUtil.equals(instrumentId, other.instrumentId) &&
			TarsUtil.equals(orderDirection, other.orderDirection) &&
			TarsUtil.equals(volumeTotalOriginal, other.volumeTotalOriginal) &&
			TarsUtil.equals(orderTimeout, other.orderTimeout) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(typeId, 1);
		_os.write(requestId, 2);
		_os.write(brokerId, 3);
		_os.write(userId, 4);
		_os.write(instrumentId, 5);
		_os.write(orderDirection, 6);
		_os.write(volumeTotalOriginal, 7);
		_os.write(orderTimeout, 8);
	}


	public void readFrom(TarsInputStream _is) {
		this.typeId = _is.readString(1, true);
		this.requestId = _is.read(requestId, 2, true);
		this.brokerId = _is.readString(3, true);
		this.userId = _is.readString(4, true);
		this.instrumentId = _is.readString(5, true);
		this.orderDirection = _is.read(orderDirection, 6, true);
		this.volumeTotalOriginal = _is.read(volumeTotalOriginal, 7, true);
		this.orderTimeout = _is.read(orderTimeout, 8, false);
	}

}
