// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.web.servant.center;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class orderOpenResponse {

	@TarsStructProperty(order = 1, isRequire = true)
	public String typeId = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public int requestId = 0;
	@TarsStructProperty(order = 3, isRequire = true)
	public int errcode = 0;
	@TarsStructProperty(order = 4, isRequire = true)
	public String errmsg = "";
	@TarsStructProperty(order = 5, isRequire = true)
	public double tradeVolume = 0D;
	@TarsStructProperty(order = 6, isRequire = true)
	public double tradePrice = 0D;
	@TarsStructProperty(order = 7, isRequire = true)
	public double tradeCommission = 0D;
	@TarsStructProperty(order = 8, isRequire = true)
	public String tradeDate = "";
	@TarsStructProperty(order = 9, isRequire = true)
	public String tradeTime = "";

	public String getTypeId() {
		return typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	public int getRequestId() {
		return requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	public int getErrcode() {
		return errcode;
	}

	public void setErrcode(int errcode) {
		this.errcode = errcode;
	}

	public String getErrmsg() {
		return errmsg;
	}

	public void setErrmsg(String errmsg) {
		this.errmsg = errmsg;
	}

	public double getTradeVolume() {
		return tradeVolume;
	}

	public void setTradeVolume(double tradeVolume) {
		this.tradeVolume = tradeVolume;
	}

	public double getTradePrice() {
		return tradePrice;
	}

	public void setTradePrice(double tradePrice) {
		this.tradePrice = tradePrice;
	}

	public double getTradeCommission() {
		return tradeCommission;
	}

	public void setTradeCommission(double tradeCommission) {
		this.tradeCommission = tradeCommission;
	}

	public String getTradeDate() {
		return tradeDate;
	}

	public void setTradeDate(String tradeDate) {
		this.tradeDate = tradeDate;
	}

	public String getTradeTime() {
		return tradeTime;
	}

	public void setTradeTime(String tradeTime) {
		this.tradeTime = tradeTime;
	}

	public orderOpenResponse() {
	}

	public orderOpenResponse(String typeId, int requestId, int errcode, String errmsg, double tradeVolume, double tradePrice, double tradeCommission, String tradeDate, String tradeTime) {
		this.typeId = typeId;
		this.requestId = requestId;
		this.errcode = errcode;
		this.errmsg = errmsg;
		this.tradeVolume = tradeVolume;
		this.tradePrice = tradePrice;
		this.tradeCommission = tradeCommission;
		this.tradeDate = tradeDate;
		this.tradeTime = tradeTime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(typeId);
		result = prime * result + TarsUtil.hashCode(requestId);
		result = prime * result + TarsUtil.hashCode(errcode);
		result = prime * result + TarsUtil.hashCode(errmsg);
		result = prime * result + TarsUtil.hashCode(tradeVolume);
		result = prime * result + TarsUtil.hashCode(tradePrice);
		result = prime * result + TarsUtil.hashCode(tradeCommission);
		result = prime * result + TarsUtil.hashCode(tradeDate);
		result = prime * result + TarsUtil.hashCode(tradeTime);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof orderOpenResponse)) {
			return false;
		}
		orderOpenResponse other = (orderOpenResponse) obj;
		return (
			TarsUtil.equals(typeId, other.typeId) &&
			TarsUtil.equals(requestId, other.requestId) &&
			TarsUtil.equals(errcode, other.errcode) &&
			TarsUtil.equals(errmsg, other.errmsg) &&
			TarsUtil.equals(tradeVolume, other.tradeVolume) &&
			TarsUtil.equals(tradePrice, other.tradePrice) &&
			TarsUtil.equals(tradeCommission, other.tradeCommission) &&
			TarsUtil.equals(tradeDate, other.tradeDate) &&
			TarsUtil.equals(tradeTime, other.tradeTime) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(typeId, 1);
		_os.write(requestId, 2);
		_os.write(errcode, 3);
		_os.write(errmsg, 4);
		_os.write(tradeVolume, 5);
		_os.write(tradePrice, 6);
		_os.write(tradeCommission, 7);
		_os.write(tradeDate, 8);
		_os.write(tradeTime, 9);
	}


	public void readFrom(TarsInputStream _is) {
		this.typeId = _is.readString(1, true);
		this.requestId = _is.read(requestId, 2, true);
		this.errcode = _is.read(errcode, 3, true);
		this.errmsg = _is.readString(4, true);
		this.tradeVolume = _is.read(tradeVolume, 5, true);
		this.tradePrice = _is.read(tradePrice, 6, true);
		this.tradeCommission = _is.read(tradeCommission, 7, true);
		this.tradeDate = _is.readString(8, true);
		this.tradeTime = _is.readString(9, true);
	}

}
