// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.web.servant.center;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class tradeItem {

	@TarsStructProperty(order = 1, isRequire = true)
	public String tradeId = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public int direction = 0;
	@TarsStructProperty(order = 3, isRequire = true)
	public double price = 0D;
	@TarsStructProperty(order = 4, isRequire = true)
	public int volume = 0;
	@TarsStructProperty(order = 5, isRequire = true)
	public String tradeDate = "";
	@TarsStructProperty(order = 6, isRequire = true)
	public String tradeTime = "";

	public String getTradeId() {
		return tradeId;
	}

	public void setTradeId(String tradeId) {
		this.tradeId = tradeId;
	}

	public int getDirection() {
		return direction;
	}

	public void setDirection(int direction) {
		this.direction = direction;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getVolume() {
		return volume;
	}

	public void setVolume(int volume) {
		this.volume = volume;
	}

	public String getTradeDate() {
		return tradeDate;
	}

	public void setTradeDate(String tradeDate) {
		this.tradeDate = tradeDate;
	}

	public String getTradeTime() {
		return tradeTime;
	}

	public void setTradeTime(String tradeTime) {
		this.tradeTime = tradeTime;
	}

	public tradeItem() {
	}

	public tradeItem(String tradeId, int direction, double price, int volume, String tradeDate, String tradeTime) {
		this.tradeId = tradeId;
		this.direction = direction;
		this.price = price;
		this.volume = volume;
		this.tradeDate = tradeDate;
		this.tradeTime = tradeTime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(tradeId);
		result = prime * result + TarsUtil.hashCode(direction);
		result = prime * result + TarsUtil.hashCode(price);
		result = prime * result + TarsUtil.hashCode(volume);
		result = prime * result + TarsUtil.hashCode(tradeDate);
		result = prime * result + TarsUtil.hashCode(tradeTime);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof tradeItem)) {
			return false;
		}
		tradeItem other = (tradeItem) obj;
		return (
			TarsUtil.equals(tradeId, other.tradeId) &&
			TarsUtil.equals(direction, other.direction) &&
			TarsUtil.equals(price, other.price) &&
			TarsUtil.equals(volume, other.volume) &&
			TarsUtil.equals(tradeDate, other.tradeDate) &&
			TarsUtil.equals(tradeTime, other.tradeTime) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(tradeId, 1);
		_os.write(direction, 2);
		_os.write(price, 3);
		_os.write(volume, 4);
		_os.write(tradeDate, 5);
		_os.write(tradeTime, 6);
	}


	public void readFrom(TarsInputStream _is) {
		this.tradeId = _is.readString(1, true);
		this.direction = _is.read(direction, 2, true);
		this.price = _is.read(price, 3, true);
		this.volume = _is.read(volume, 4, true);
		this.tradeDate = _is.readString(5, true);
		this.tradeTime = _is.readString(6, true);
	}

}
