// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.web.servant.center;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class TraderServantPrxCallback extends TarsAbstractCallback {

	public abstract void callback_userLogin(int ret, userLoginResponse rsp);

	public abstract void callback_userLogout(int ret, userLogoutResponse rsp);

	public abstract void callback_orderOpen(int ret, orderOpenResponse rsp);

	public abstract void callback_orderClose(int ret, orderCloseResponse rsp);

	public abstract void callback_instrumentQuery(int ret, instrumentQueryResponse rsp);

	public abstract void callback_instrumentCommissionQuery(int ret, instrumentCommissionQueryResponse rsp);

	public abstract void callback_marketDataQuery(int ret, marketDataQueryResponse rsp);

}
